mifix(ui): resolve button alignment issue

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,4 +1,16 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
-npx lint-staged
+# Run linting
+npm run lint
+if [ $? -ne 0 ]; then
+  echo "Linting failed. Commit aborted."
+  exit 1
+fi
+
+# Run tests
+# npm run test
+# if [ $? -ne 0 ]; then
+#   echo "Tests failed. Commit aborted."
+#   exit 1
+# fi
